version: "3.9"

services:
  web:
    build: .
    container_name: django_scraper
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=*
    restart: always